[project]
dependencies = [
  "Django==6.0.6",
  "nikkei-utils==1.10.0",
  "sentry-sdk==2.64.0",
  "uWSGI==2.0.31",
  "whitenoise==6.12.0",
]
description = "Add your description here"
name = "reno_test_1"
readme = "README.md"
requires-python = "==3.13.*"
version = "0.1.0"

[[tool.uv.index]]
name = "nikkei"
url = "https://pypi.n8s.jp/9c346c40-7d2f-473e-9580-d41ee07d25ea/packages/simple"

[tool.uv.sources]
nikkei-utils = [{index = "nikkei"}]

[tool.uv]
# 変更する場合は、.github/renovate.jsonのminimumReleaseAgeも合わせて変更してください。
# 緊急のパッチを当てる際は、exclude-newer-packageで個別に対応してください。
exclude-newer = "3 days"
exclude-newer-package = {nikkei-utils = false}

[dependency-groups]
dev = [
  "coverage==7.15.0",
  "mypy==1.20.2",
  "pytest==9.1.1",
  "pytest-cov==7.1.0",
  "pytest-django==4.12.0",
  "pytest-mock==3.15.1",
  "pytest-randomly==4.1.0",
  "pytest-xdist==3.8.0",
  "responses==0.26.2",
  "ruff==0.15.20",
  "taskipy==1.14.1",
  "testfixtures==11.0.0",
  "tox==4.56.1",
  "tox-uv==1.35.2",
]

[tool.ruff]
exclude = [
  "htmlcov",
  "**/.mypy_cache",
  "**/.pytest_cache",
  ".tox",
  "venv",
  ".venv",
  "reno_test_1/*/migrations/*",
  "reno_test_1/reno_test_1/wsgi.py",
]
include = ["*.py"]

lint.ignore = [
  "E203", # Whitespace before ':'
  "E501", # Line too long (82 &gt; 79 characters)
  "D105", # undocumented-magic-method
  "D107", # undocumented-public-init
  "D205", # blank-line-after-summary
  "D415", # ends-in-punctuation
]

lint.select = [
  "F", # Pyflakes
  "E", # pycodestyle error
  "W", # pycodestyle warning
  "I", # isort
  "B", # flake8-bugbear
  "C", # flake8-comprehensions
  "UP", # pyupgrade  # "D", # pydocstyle（必要な場合は外す）
]

line-length = 99
src = ["reno_test_1"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.coverage.report]
include = ["reno_test_1/**"]
omit = [
  "reno_test_1/*/tests/**",
  "reno_test_1/*/tests.py",
  "reno_test_1/reno_test_1/settings/**",
  # ユニットテストでは実行されない Django のエントリポイントは対象外にする
  "reno_test_1/reno_test_1/asgi.py",
  "reno_test_1/reno_test_1/wsgi.py",
  "reno_test_1/manage.py",
]
skip_covered = true

[tool.taskipy.tasks]
createsuperuser = "python reno_test_1/manage.py createsuperuser"
format = '''
ruff format reno_test_1/
ruff check reno_test_1/ --fix
'''
migrate = "python reno_test_1/manage.py migrate"
minimum-format = '''
ruff check reno_test_1/ --ignore B,C,UP,D --fix
ruff format reno_test_1/
'''
runserver = "DJANGO_SETTINGS_MODULE=reno_test_1.settings.local python reno_test_1/manage.py runserver"
unsafe-format = '''
ruff check reno_test_1/ --unsafe-fixes --fix
ruff format reno_test_1/
'''

[tool.mypy]
ignore_missing_imports = true
