[tox]
envlist = py, lint, format, mypy
skipsdist = true
#isolated_build = false
setupdir = ./

[testenv:py]
commands =
  pytest ./reno_test_1 -n logical --dist loadfile --showlocals --durations=5 --junitxml=junit.xml --cov-report=term-missing --cov-report=html:htmlcov --cov=reno_test_1

[testenv:lint]
commands =
  ruff check --output-format=github --ignore D reno_test_1

[testenv:format]
commands =
  ruff format --check --diff reno_test_1

[testenv:mypy]
commands =
  mypy --install-types --non-interactive reno_test_1

[pytest]
junit_family = xunit2
DJANGO_SETTINGS_MODULE = reno_test_1.settings.test

