[tox]
envlist = py, lint, format, mypy
skipsdist = true
#isolated_build = false
setupdir = ./

[testenv:py]
commands =
  pytest ./aaa_2 -n logical --dist loadfile --showlocals --durations=5 --junitxml=junit.xml --cov-report=term-missing --cov-report=html:htmlcov --cov=aaa_2

[testenv:lint]
commands =
  ruff check --output-format=github --ignore D aaa_2

[testenv:format]
commands =
  ruff format --check --diff aaa_2

[testenv:mypy]
commands =
  mypy --install-types --non-interactive aaa_2

[pytest]
junit_family = xunit2
DJANGO_SETTINGS_MODULE = aaa_2.settings.test

